version: '3'
services:

    # The Application
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "SERVICE_NAME=eskimi"
            - "SERVICE_TAGS=dev"
        depends_on:
            - database
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - eskimi-network

    # The Web Server
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - app
        ports:
            - "8080:80"
        networks:
            - eskimi-network

    # The Database
    database:
        image: mysql:latest
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=eskimi_db"
            - "MYSQL_USER=root"
            - "MYSQL_PASSWORD=secret"
            - "SERVICE_TAGS=dev"
            - "SERVICE_NAME=mysql"
        ports:
            - "33061:3306"
        networks:
            - eskimi-network

    # Phpmyadmin
    pma:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        container_name: eskimi-phpmyadmin
        environment:
            PMA_HOST: database
            PMA_USER: root
            UPLOAD_LIMIT: 30M
        ports:
            - "8090:80"
        networks:
            - eskimi-network

#Docker Networks
networks:
    eskimi-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
